/**
 * DOT — "What would help you" recommendations.
 *
 * Fixed symptom -> recommendation mapping table, computed entirely in code.
 * NEVER free-generated by an LLM — this is medical-adjacent advice, so it
 * must be deterministic and testable, same philosophy as recognition.ts.
 *
 * Phrasing rule: "ask about" / "worth checking" only — never "you have",
 * "you need", or "take X". Max 4 items, ordered by relevance (most
 * actionable / most clinically load-bearing first).
 */

import { SessionData } from "./session";

export interface Recommendation {
  id: string;
  text: string;
}

const HEAVY_OR_IRREGULAR: ReadonlySet<string> = new Set([
  "irregular",
  "heavier_or_lighter",
  "closer_together",
  "skipping",
]);

const TIME_WORK_BARRIER = /\b(time off|work|shift|hours|childcare|cover|rota|leave)\b/i;

function present(data: SessionData, id: string): boolean {
  return data.impacts[id] !== undefined;
}

export function computeRecommendations(data: SessionData): Recommendation[] {
  const recs: Recommendation[] = [];

  const heavyOrIrregularPeriods =
    data.menstrualChange !== null && HEAVY_OR_IRREGULAR.has(data.menstrualChange);
  const fatiguePresent = present(data, "fatigue");
  const moodPresent = present(data, "anxiety") || present(data, "low_mood_irritability");
  const brainFogPresent = present(data, "brain_fog");
  const nightSweatsOrSleep = present(data, "night_sweats") || present(data, "sleep");
  const statedTimeBarrier = data.heldBack !== null && TIME_WORK_BARRIER.test(data.heldBack);

  if (heavyOrIrregularPeriods && fatiguePresent) {
    recs.push({
      id: "iron",
      text: "Ask your healthcare practitioner to check your iron (ferritin) and blood count. Heavy periods often lower iron, which makes tiredness and brain fog worse.",
    });
  }

  if (fatiguePresent && moodPresent && brainFogPresent) {
    recs.push({
      id: "thyroid",
      text: "Ask about a thyroid check, a simple blood test that rules out an overlap.",
    });
  }

  if (statedTimeBarrier) {
    recs.push({
      id: "phone-appointment",
      text: "You can ask for a phone appointment if getting time off is hard.",
    });
  }

  if (nightSweatsOrSleep) {
    recs.push({
      id: "cooler-room",
      text: "Worth trying tonight: a cooler room, and less caffeine after 2pm.",
    });
  }

  return recs.slice(0, 4);
}
